-- Seed: sample builds for Build Hub
-- Generated by seed-builds.mjs

-- Clean up previous seed data before inserting fresh builds
DELETE FROM build_tags WHERE build_id IN (SELECT id FROM builds WHERE author_id = 'seed-author');
DELETE FROM builds WHERE author_id = 'seed-author';

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('6i4e6316166j', 'seed-author', 'ESO Toolkit Team', 0, 'Meta Trash DK — Magicka DPS', 'Dragonknight Magicka DPS with Nightblade and Arcanist subclassing. Perfected Sul-Xan''s Torment + Velothi Ur-Mage''s Amulet. Front bar dual daggers, back bar bow.', 'dragonknight', 'magicka-dps', 'pve', 'TY5BboMwEEWvYv31qDI2EONdpOyqVJXSHWLhgAsuwals0y4ipB6iJ-xJKmgX2YzezOi_mRs-oDOCh8bRJsNegokDOzyyn69vdjS9a0fDDs8nEDpoHILpr370rh_S_Zp9ujSwp3V8vpjOMuM7tg-t8S4mFudzezExOt8_gGDb7WYbL9A1p0xR2RACtCAEA12jm_1kAwjjYN6cSyCcg01Xj4YQoesb_ASNv29PNs3vIJgEXecVZQXxhjBFaKTB2VcQ4gh9A_8vgpclJ2QrKV4QxEqV5AQJLZUqdoR8pSrjhAJaiirfLVtkM0hVVmJrZcULsRlynq-51SCUyjZDzqUSd4ZlaZZf', 0, '2026-03-16 05:28:55', '2026-03-16 05:28:55');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('6i4e6316166j', 'meta');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('6i4e6316166j', 'group-content');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('6i4e6316166j', 'subclass');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('6i4e6316166j', 'dual-dagger');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('0m152p0g5r52', 'seed-author', 'ESO Toolkit Team', 0, 'Trial Healer — Restoring Templar', 'High-sustain Templar healer for 12-man trials. Jorvuld''s Guidance + Spaulder of Ruin. Maximises healing done and Major/Minor Mending uptime.', 'templar', 'healer', 'pve', 'PY5NbsIwEIWvYr1NF52iieME4gsUdQnsoizcxBCL4CA7YYMi9RA9YU9S4f5sRm80733z7rhBZwQPjUNwZhBbawYbxNfHp9jZOI3B-ZM42Mt1MAGEDhpbd-pf4hwn4_zfSfQptxJvY7jNQ_cUxevsOuNbK57F_mrmobNBjEexm51fgWBbaEVo4wBdV5QxZVlDCKlPMNA13oOdRg-CCafRO_OQ_eO5HY5oCBG6vsNf_svv7TRfH_4JupZMuaKMG8IlQsNMYfSm7UGIZ-g7-HdIKYuSkCWlmCChZbkpNoQcWmbrsiAoaMVcKUKRfLJaUiQRFHPJaVXM6-qHIGUpE0FJzjeJkFdcFYmgWMp8WZZm-QY', 0, '2026-03-16 05:28:55', '2026-03-16 05:28:55');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0m152p0g5r52', 'trials');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0m152p0g5r52', 'healer');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0m152p0g5r52', 'templar');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0m152p0g5r52', 'support');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('6a6k3w35446l', 'seed-author', 'ESO Toolkit Team', 0, 'Stamina Warden DD — Animal Companions', 'Stamina Warden for group and solo content. Pillar of Nirn + Deadly Strike. Heavy DoT-focused rotation with Subterranean Assault and Bird of Prey.', 'warden', 'stamina-dps', 'pve', 'TcxBasMwEAXQq4i_7SRIlh1s7UK9bSm40IXJQrWVRsSWgiQ3lGDoIXrCnqTETaGb4c8w_13wDiUIDgpN0qN1mr3o0BvH6pp9f36xrbOjHti9H0_aWe8iCD0Unuww6MD8nj3a4Ngdq43uhw_WpGCPZs1q_7za-26KpmfBJ52sd-xs04E102syIWhntGPbGPU0pDUIpoMqCF0coFqRkZAk8h0hQElC0FAtzt73KzPsQQimf5t06EHwocOOEKHaC9wIhQdtHWtMmk4g6ATVcso45VdvjFBIB2uuSjxCXcBvo9xwkRMEVFlUVUXIlltREuSS8oKQQ-Vclhmh-P3j81JZBFluqmxZZcWL7E-Q4iYIyRfhaol_wjzv5h8', 0, '2026-03-16 05:28:55', '2026-03-16 05:28:55');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('6a6k3w35446l', 'stamina');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('6a6k3w35446l', 'warden');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('6a6k3w35446l', 'dot');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('6a6k3w35446l', 'nature');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('2j4d5a5y6h3u', 'seed-author', 'ESO Toolkit Team', 0, 'Magicka Sorcerer — Daedric Surge', 'Classic Magicka Sorcerer for all content. Mother''s Sorrow + Whorl of the Depths. Pet-based sustain with Frenzied Momentum and Bound Aegis.', 'sorcerer', 'magicka-dps', 'pve', 'TY6xasMwEIZf5fiXDr0GW5LdWFtL1kIhQwfjQXUUSySxgyQ3QzD0IfqEfZJiJ0OX4-Pnv-_uii_onNFD4810vj0Y2g6htcEG-v3-oY2xu-Bb2o6hs2Ds5uKQnA0PcW6G4UKP9OGGcKRhT8lZ2thzcnFF7zZRHGMyvqeLT45eh7Hf0YvtfFyBYVtowWjjEbqWrLhoGGHJgoGu4XznnuxxD8ZnsGno5_smHJasYUTo-or-tPzue9raNJ7BMAm6VhXnBWcN4xShkZy3sygeoK_I7kOVUihGDi2UlBlDLCTWDAktpMglQ81UPq8ZxUyqEtOyshhklRXiZpAiuxukzMubQeXlzaBKWZT_DNPUTH8', 0, '2026-03-16 05:28:55', '2026-03-16 05:28:55');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2j4d5a5y6h3u', 'sorcerer');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2j4d5a5y6h3u', 'pets');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2j4d5a5y6h3u', 'magicka');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2j4d5a5y6h3u', 'beginner-friendly');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('5p4x6y032i29', 'seed-author', 'ESO Toolkit Team', 0, 'Necromancer Tank — Bone Tyrant', 'Necromancer tank for veteran trials and arenas. Saxhleel Champion + Crimson Oath''s Rive. Ultimate-stacking with Stalwart Guard and Bone Shield.', 'necromancer', 'tank', 'pve', 'Nc5NTsMwEAXgq1hvw4KhshPnz0u6B4mWVZTFKFgkSuxUjqlAVSQOwQk5CZJbNqO3ed-bC84wiuBh8GT7sDj2vQ3iyH4Sv98_4nHxVhy_AvsIwhsMDvw5zNbOYj-wO42LF_diH0a3Ll48cxzuVvEynu1OvM5xdBztwxq5n0b_LtKCiOynHQi2hykJ_TrDtKogVZKqOkKAkYTAMC38Et5AGN3JhpFnEJbQoyOsMO0F3sEg_Xqw8eMEAkeYVlKpSXYEt8KAY1g89wMI6wRzgbwdpeosrwgqxTJvCFmKWmpCDpPXWSEJOqVSE4prqWq21PpXGpXdlKqu85tS1bJIis5kUV6VRjZFUrTMsnzbtm77Aw', 0, '2026-03-16 05:28:55', '2026-03-16 05:28:55');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5p4x6y032i29', 'tank');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5p4x6y032i29', 'necromancer');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5p4x6y032i29', 'veteran');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5p4x6y032i29', 'trials');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('5u5s3f6n440e', 'seed-author', 'ESO Toolkit Team', 0, 'Arcanist Magicka DPS — Herald of the Tome', 'Arcanist Magicka DPS with Runic Sunder and Fatecarver. New player-friendly rotation with strong passive Crux generation. Whorl of the Depths + Deadly Strike.', 'arcanist', 'magicka-dps', 'pve', 'Nc7PSsNAEAbwV1m-q1PZ_N_sTRTxUhHrLfSwJtMmNNmUzaZaSsCH8Al9Ekmsl2H4-ObHXHCCDggWGneuNLYZvFibfVMejHh42Yifr2_xxM60leh3wtcs3vqOQaig8TraphSb0VbsxI14NJ5L407shOu98U1vb8Uzf6yOrTmzW-1cw7Zqz-LejZ9iz5bdXwkELqEzQjm00EWgKMgplFuCgw4JzkAXqJt9veJ2B8K7Y9_b-Y3RduywJQzQxQW2g8baNFZs2I9HEIyHLuKcgoRmsBug4euGZ2Y4QF8gryNQkZQpIZjXMM8yQrikcSQJ0V-qFCGGjmWcZIRkDnOVZtNytjBRLpPwqiQqDq9Kkku1KLGMVPiPZOqKpFGaTtO0nX4B', 0, '2026-03-16 05:28:55', '2026-03-16 05:28:55');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5u5s3f6n440e', 'arcanist');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5u5s3f6n440e', 'magicka');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5u5s3f6n440e', 'new-player');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5u5s3f6n440e', 'necrom');

