-- Seed: sample builds for Build Hub
-- Generated by seed-builds.mjs

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('1j3w0d6f430a', 'seed-author', 'ESO Toolkit Team', 0, 'Meta Trash DK — Magicka DPS', 'Dragonknight Magicka DPS with Nightblade and Arcanist subclassing. Perfected Sul-Xan''s Torment + Velothi Ur-Mage''s Amulet. Front bar dual daggers, back bar bow.', 'dragonknight', 'magicka-dps', 'pve', 'Tc5NasNADAXgqwxvLcr82GNbu0B2JaWQ7owXE9u1p04mxTNpF8HQQ_SEPUmp00U2AumhT7riA6wIAYxdn5x4mV0cxfZR_Hx9i50bfDs5sX3eg9CBsZ3dcA5T8MOY7mPx6dMonv7Gh6PreuFCJzZz64KPScTLoT26GH0YHkDo2_VmG4_gWpIqyTaEGawJswPX6C7h1M8gTKN78z6BcJj7dA5oCBFcXxFOYNy-3ffp8g6CS-A6q0jlJBvCKYKRRt-_ghAn8BXyvyht86ogKLApK5sRNFibUlqCAWfS6IKQgY2SlSXkYGOrQi_rykqYsjTV2mqli3wVjFLSrIJRpS5vQlZYfScsS7P8Ag', 0, '2026-03-16 04:26:43', '2026-03-16 04:26:43');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1j3w0d6f430a', 'meta');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1j3w0d6f430a', 'group-content');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1j3w0d6f430a', 'subclass');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1j3w0d6f430a', 'dual-dagger');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('0j416k6n0r64', 'seed-author', 'ESO Toolkit Team', 0, 'Trial Healer — Restoring Templar', 'High-sustain Templar healer for 12-man trials. Jorvuld''s Guidance + Spaulder of Ruin. Maximises healing done and Major/Minor Mending uptime.', 'templar', 'healer', 'pve', 'PY5BboMwEEWvYv1NF51GNiYN-AKNukyyQyxccMCKYyIbskFIPURP2JNUkNDN6Ekz_80fcYcSBA-FU7Dasb3RzgT2-_3DDib2XbC-YSdzvTkdQKihsLdN-xaH2Gvr1xVrl9yGfXbhPrj6JbKPwdbaV4a9suNND642gXVndhis34BgKqiUUEUHVeQkOAlREsLSJ2ioAl_B9J0HQYem81bP2M7PjTujJESoYoS__pc_mn64zfc9VJFwkikJXhKuEQq6D53XVQtCvECN4M-RJMn7liAelBOShbY5QS6UCkL6oIywXUjyaYmshp1cDbvdasjkasiy1ZDLp0FyPk1TOf0B', 0, '2026-03-16 04:26:43', '2026-03-16 04:26:43');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0j416k6n0r64', 'trials');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0j416k6n0r64', 'healer');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0j416k6n0r64', 'templar');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0j416k6n0r64', 'support');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('5q3o3g13236g', 'seed-author', 'ESO Toolkit Team', 0, 'Stamina Warden DD — Animal Companions', 'Stamina Warden for group and solo content. Pillar of Nirn + Deadly Strike. Heavy DoT-focused rotation with Subterranean Assault and Bird of Prey.', 'warden', 'stamina-dps', 'pve', 'TczNSsNAHATwV1nm6r-yX6lmb8VcFSGCh9DD2mzt0mS3bDYWKQEfwif0SSQawcswDMzvgjcYQQgwqLPtfbDs2abWBVZV7Ovjk22C723H7mJ_ssHHMIDQwuDRd51NLO7Zg0-BXbHK2bZ7Z3VO_uiuWRWfVvu4GwfXshSzzT4Gdvb5wOrxJbuUbHA2sM0w2LHL1yC4HUxB2A0dTCMkCUVCbwkJRhGShWlwjrFduW4PQnLt62hTC0JMO2wJA0xzQehhcG99YLXL4wkEm2EaTpKTnr1-gEE-eDcrwxHmAr6EFkpogoDRvCwLgoQRNyWXBDVvshAEPTel1oRibnrNp5_LIkipFkHd_gqq5MWfoCVfBKn1P2GattM3', 0, '2026-03-16 04:26:43', '2026-03-16 04:26:43');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5q3o3g13236g', 'stamina');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5q3o3g13236g', 'warden');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5q3o3g13236g', 'dot');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('5q3o3g13236g', 'nature');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('1s23013j5v5b', 'seed-author', 'ESO Toolkit Team', 0, 'Magicka Sorcerer — Daedric Surge', 'Classic Magicka Sorcerer for all content. Mother''s Sorrow + Whorl of the Depths. Pet-based sustain with Frenzied Momentum and Bound Aegis.', 'sorcerer', 'magicka-dps', 'pve', 'PY5BasMwEEWvMvxNF50GW1JCol1LtoVCFl0YL1RHsUQSK0hyswiGHqIn7EmKnbqb4fP482Zu-IQuGR00Xk3rm6OhXYiNjTbSz9c3bY3dR9_Qro-tBWM_FkN2Nj6ksRnDlR7p3YV4onCg7Cxt7SW7tKA3myn1KRvf0dVnRy-h7_b0bFufFmDYBlowmnSCriQrXtaMOLFooCs437onezqA8RFtDt1438TjxGpGgq5u6M7T776jnc39BQyToSu14XLJRc04J2hk5-0oSkfoG4q_IdSqXDNKaCFFUTLEPW0YckqlZKgpScVY3tlmmFbuBinEajbIYjbI1WxQxWxQ_wa1HoahHn4B', 0, '2026-03-16 04:26:43', '2026-03-16 04:26:43');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1s23013j5v5b', 'sorcerer');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1s23013j5v5b', 'pets');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1s23013j5v5b', 'magicka');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1s23013j5v5b', 'beginner-friendly');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('2o0y3i711n4n', 'seed-author', 'ESO Toolkit Team', 0, 'Necromancer Tank — Bone Tyrant', 'Necromancer tank for veteran trials and arenas. Saxhleel Champion + Crimson Oath''s Rive. Ultimate-stacking with Stalwart Guard and Bone Shield.', 'necromancer', 'tank', 'pve', 'Pc6xasMwEMbxVxHf0qHXYCe2E2ts9haadDIeDkXEwpYUJDW0BEMfok_YJynYjZfjv9zv7oYrZE5wkHjRKnjLTukgjux68fv9I5690-L4FdglEE6QOPBnN2g9iH3H9mK8E49iH4yN3olXTt1DFG_mqlfifUjGctJPMbHqjTuL6YJI7PoVCFpBVgQVB8gmLymvKN-2hACZEQJDNnA-nEAw9qKD4QEEHxRaQoRsbnAWEtOvB50-LiBwgmwyqgrKWoKNkOAUvGPVgRB7yBuy_7Gp18WOkM9VE9ZTlRlhM1dOKOZaE8q5NuO0chfK4i6U5SJUi7BdhN0i1OM4tuMf', 0, '2026-03-16 04:26:43', '2026-03-16 04:26:43');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2o0y3i711n4n', 'tank');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2o0y3i711n4n', 'necromancer');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2o0y3i711n4n', 'veteran');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2o0y3i711n4n', 'trials');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('386m1l6a032i', 'seed-author', 'ESO Toolkit Team', 0, 'Arcanist Magicka DPS — Herald of the Tome', 'Arcanist Magicka DPS with Runic Sunder and Fatecarver. New player-friendly rotation with strong passive Crux generation. Whorl of the Depths + Deadly Strike.', 'arcanist', 'magicka-dps', 'pve', 'Nc7PSsNAEMfxVxl-V6eS_233Jop4qYj1FnrYJtNmabIpm021lIAP4RP6JNLGXIbvYebDXHCCChkWCg-u0NZ0nlZ6b4qDpqe3Nf1-_9CLOF2X1O7IV0IfbSNglFB4760paN3bUhzd0bP2Umh3Ekeu9dqb1t7Tq3zOjrU-i5vtnBFb1md6dP0X7cWKG5fAkAJqzii6GioPFxwuOQo2DAcVMZyGylGZfTWTegfG1olv7fWN3jbisGF0UPkFtoHCShtLa_H9EQztofJkyWHKV7DpoOArI1emO0BdEPyPJArimBGOlTGisZaM-FZJxEjGShnpWIvhdjIJaTgJaTIJ6XwSsmASsngSsmwYhs3wBw', 0, '2026-03-16 04:26:43', '2026-03-16 04:26:43');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('386m1l6a032i', 'arcanist');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('386m1l6a032i', 'magicka');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('386m1l6a032i', 'new-player');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('386m1l6a032i', 'necrom');

