-- Seed: sample builds for Build Hub
-- Generated by seed-builds.mjs

-- Clean up previous seed data before inserting fresh builds
DELETE FROM build_tags WHERE build_id IN (SELECT id FROM builds WHERE author_id = 'seed-author');
DELETE FROM builds WHERE author_id = 'seed-author';

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('4t4a3l14285t', 'seed-author', 'ESO Toolkit Team', 0, 'Meta Trash DK — Magicka DPS', 'Dragonknight Magicka DPS with Nightblade and Arcanist subclassing. Perfected Sul-Xan''s Torment + Velothi Ur-Mage''s Amulet. Front bar dual daggers, back bar bow.', 'dragonknight', 'magicka-dps', 'pve', 'TY7NSsQwFIVfJZz1RfLTnyQ7YXYyIoy70kWmrW3tTEaajC6Ggg_hE_ok0ljBzeW7J5zv5oZ3WEHwsNh30bHn2YWB7R7Y9-cX27t-bCbHdk8HEFpY7GbXX_zkx36I_5_ZxxgH9rjGx5NrO-Z8y-7nxvkxRBaux-bkQhh9fwdC16SbTTjBVpyEpqImzLCSMDvYCu3Vn7sZhGlwr-MYQTjOXbx41IQAW93gz7D4_e2hi9c3EFyErTJDIideE84BFnEYuxcQwgR7A9-G5EXBCWIlzXOCXMkoTlCwSuu8JGQrGcEJOaySJiuXVEkGpQsj06oMz2UyZDxbe6tBai2SIeNKy3-GhdBvClGqMiuSw5RS6ORIoUqShJpQbGgIesOSYDbMCGIzlAQhE8o1_euJZamXHw', 0, '2026-03-16 06:06:54', '2026-03-16 06:06:54');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('4t4a3l14285t', 'meta');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('4t4a3l14285t', 'group-content');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('4t4a3l14285t', 'subclass');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('4t4a3l14285t', 'dual-dagger');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('1l6w6c4l4m11', 'seed-author', 'ESO Toolkit Team', 0, 'Trial Healer — Restoring Templar', 'High-sustain Templar healer for 12-man trials. Jorvuld''s Guidance + Spaulder of Ruin. Maximises healing done and Major/Minor Mending uptime.', 'templar', 'healer', 'pve', 'PY5BbsIwEEWvYv1NF50ie-KExBco6hLYIRYumCRqcJCdsEGReoiesCepMKEb69n-_83ccIVRBA-DbWhtJ1bOdi6I3-8fsXZx6EPra7F150tnAwhHGKzaunmLYxxs659fokm9hfjow3Xsji9RvI_t0fqDE69ic7Fjd3RB9CexHlu_AMEdYDThEDuYXUVKklJ7Qkj7BAuzw2dwQ-9BsKHufWvv2NyHu-6EPSHC7G7w5__lN24YL_f8ALNjSZkmJfeEc4SBHULv7aEBIX7B3CDng5nzgqASaUlgGC7KvCRkMKyWRU7QMFrKShPylONqSpVk0FIWMl21lMvqYWAuOBk0y6xMhqySVZ4MWjJn00SoZ4XiSvEyOVRZaPWQpFedLHfMJKGYURHKOVASqhlzgnoqSoLiBzMT1NxkNU376Q8', 0, '2026-03-16 06:06:54', '2026-03-16 06:06:54');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1l6w6c4l4m11', 'trials');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1l6w6c4l4m11', 'healer');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1l6w6c4l4m11', 'templar');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('1l6w6c4l4m11', 'support');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('331v2e0i0a1s', 'seed-author', 'ESO Toolkit Team', 0, 'Stamina Warden DD — Animal Companions', 'Stamina Warden for group and solo content. Pillar of Nirn + Deadly Strike. Heavy DoT-focused rotation with Subterranean Assault and Bird of Prey.', 'warden', 'stamina-dps', 'pve', 'Tc7fSsMwFAbwVwnfrWfSJO3a5m7YW0WY4MXYRVyzLaxNRpo6ZBR8CJ_QJ5F2Fb0JX86fH-eKdyhOcFBYR91ap9mrDrVxrKrY9-cXWznb6oY9-PasnfWuA6GGwrNtGh2Y37MnGxy7Y5XRdfPB1jHYk7lnlX9Z7P2u70zNgo86Wu_YxcYjW_dv0YSgndGOrbpO9028B8HsoDLCrmugNlwQl8TTLSFASULQUBtcvK8XptmDEEx96HWoQfBhhy2hg9pc4VooPGrr2NrE_gyCjlCbhERC6ei1HRTi0ZpR6U5QVyTzUywTnhI4VJGVZUkQUy0rCHJKaUZIodJEFoKQ3eaSYVqZBFksSzF9ZZlk4leQfBa4TCZhtPg_YSAcZoKLPBt74xV5kcvJGIvydsbUl4TlHFNCMUdBKOfZksD_BC5ucUng857Mh2E7_AA', 0, '2026-03-16 06:06:54', '2026-03-16 06:06:54');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('331v2e0i0a1s', 'stamina');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('331v2e0i0a1s', 'warden');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('331v2e0i0a1s', 'dot');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('331v2e0i0a1s', 'nature');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('170h22503t4o', 'seed-author', 'ESO Toolkit Team', 0, 'Magicka Sorcerer — Daedric Surge', 'Classic Magicka Sorcerer for all content. Mother''s Sorrow + Whorl of the Depths. Pet-based sustain with Frenzied Momentum and Bound Aegis.', 'sorcerer', 'magicka-dps', 'pve', 'TY5NasMwEIWvIt6mi06D9WPF1q4l20Ihiy5MFq6j2CaJHSS5WQRDD9ET9iRFcgrdDB-Ped_MDZ8wnDDA4LVu--ZYs-3oGuusYz9f32xT273rG7adXGtB2MfFMXTWPfi46cYre2Tv3ehObDyw0Fm2sZfQ-RV7s4H5yYe6H9i1Dx17Gadhz55t2_sVCLaBEYTGn2AqSYryHcGlzNUwFbq-7Z7s6QDCh7NhHOL92h1TtiN4mOqG4Zx-7we2tWG6gFAHmEqVxHPKdoSzh0HoehtF_ghzQ3YfSkuhCBxGKCkzgkgkCoKEEVJwSVCR9Log5JFUKeZUSQZZZrlYDFJkd4OUXC8GxfViUFrm-p9hJrR3RbkWMk8KXmjFy-SIoUiOSAVBL1QSioU0oVxIEvhfuyBwsbCIf91rfJ538y8', 0, '2026-03-16 06:06:54', '2026-03-16 06:06:54');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('170h22503t4o', 'sorcerer');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('170h22503t4o', 'pets');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('170h22503t4o', 'magicka');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('170h22503t4o', 'beginner-friendly');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('2d3m6b5f0n4m', 'seed-author', 'ESO Toolkit Team', 0, 'Necromancer Tank — Bone Tyrant', 'Necromancer tank for veteran trials and arenas. Saxhleel Champion + Crimson Oath''s Rive. Ultimate-stacking with Stalwart Guard and Bone Shield.', 'necromancer', 'tank', 'pve', 'Nc7BasMgHMfxV5HfZYf9V9SYmHhc7xus3Sn0IKk0IYkpxpWNEthD7An3JGM2vcgX4ffRKy4wguBh8OKaMI3WNy6wvfU9-_3-Yc-Td2z_FayPIBxhsLOf7eDcwLatHc_d5Nkj24ZunCfPXm1sH2b21l3chr0PsRttdE9ztE3f-RNLL7Bofb8BwTUwBaGZB5ha5CQKEvpACDCcECxMDT-FIwjdeHahswMIU2hwIMww9RV-hEH6687FjzMINsLUnApF_EAYZxjYGCZvmxaEuYe5gq-HEKXMNEGkLLKKIFMqrggZTFbKnBNUqkIR8ttIV0ta3ZVKyFXRZZmtii55nhQleV7clIpXeVIUlzJbFsLpruis1PlN0VpxcVP-b2VSUmpCsWZJKNcsCNWaGUHcCU4Qcm1FEPclX5bD8gc', 0, '2026-03-16 06:06:54', '2026-03-16 06:06:54');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2d3m6b5f0n4m', 'tank');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2d3m6b5f0n4m', 'necromancer');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2d3m6b5f0n4m', 'veteran');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('2d3m6b5f0n4m', 'trials');

INSERT OR IGNORE INTO builds (id, author_id, author_name, is_anonymous, title, description, eso_class, role, game_mode, build_data, vote_count, created_at, updated_at) VALUES ('0f04530s5s3e', 'seed-author', 'ESO Toolkit Team', 0, 'Arcanist Magicka DPS — Herald of the Tome', 'Arcanist Magicka DPS with Runic Sunder and Fatecarver. New player-friendly rotation with strong passive Crux generation. Whorl of the Depths + Deadly Strike.', 'arcanist', 'magicka-dps', 'pve', 'Rc_BauMwFAXQXxF325ciS7IsazfMMHTTMjTdhSxUR0lMHbnIcqclGPoR84X9kmJH027E5fLe4emMF9iCEGDxIzYutENit-7QNk-O_fqzZh_v_9iNj67bsX7P0tGzh_7kQdjB4n4MbcPWY9j5yK7Yb5d84-KLjyz2yaW2D9fszv9dPXfuzcfVPrY-7Lo39jOOr-zgg4-XIRB8A1sRmqGD3RSGipoE3xIirCBEB7vBsT0cV77bg_AYferDfMYYTj5iSxhgN2eEEyxuXRvY2qfxGQSXYDeqpqKkGTwNsEjH1s_M8AR7Bs9PYSTnmlDMUdRVRRBLqyQnyEtrDEHBKq7KilDOZW10NS1rCyNrXoqslEaJrJQ1N4uiuDTiP1KZjGip9TQRDl_HaCXMwpjKVDIrWoky36KVLAg6R0EweaAm1DnOv_kWCnGJc5v3hJym7fQJ', 0, '2026-03-16 06:06:54', '2026-03-16 06:06:54');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0f04530s5s3e', 'arcanist');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0f04530s5s3e', 'magicka');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0f04530s5s3e', 'new-player');
INSERT OR IGNORE INTO build_tags (build_id, tag) VALUES ('0f04530s5s3e', 'necrom');

