blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://discord.gg/mMjwcQYFdc
    about: Join Discord and privately contact a maintainer. Do not post vulnerability details publicly.
