-- Add source column to track knowledge reliability
ALTER TABLE knowledge_docs ADD COLUMN source TEXT NOT NULL DEFAULT 'verified';

-- Tag existing seed data as verified game mechanics
UPDATE knowledge_docs SET source = 'verified';

-- ─── DPS Fundamentals ───────────────────────────────────────────────────────

INSERT INTO knowledge_docs (doc_type, title, content, source) VALUES

('mechanic', 'DPS Rotation Fundamentals', 'A DPS rotation is built around two ability types: damage over time (DoTs) and direct damage (spammables). DoTs are abilities that deal damage over a duration — one cast of a DoT that deals more total damage than one cast of your spammable is worth slotting. The rotation priority is: keep all DoTs active, reapply them as they expire (not early), and use your spammable as filler when nothing needs refreshing. Reapplying a DoT early wastes its remaining ticks and reduces its effective value below that of a spammable cast.', 'verified'),

('mechanic', 'Global Cooldown and Time on Target', 'ESO limits ability casts to one per second via the Global Cooldown (GCD). Maximizing DPS means casting something every single GCD — every second spent not dealing damage is a significant loss. This concept is called "time on target" or "always be casting." Spamming random abilities is better than standing idle. A well-executed rotation fires one ability per second with zero gaps.', 'verified'),

('mechanic', 'Light Attack Weaving Technique', 'Light attack weaving places a light attack between each ability cast while maintaining the 1-second GCD rhythm. The technique uses the "queue window" — the last 400-600ms of the GCD where your next input is queued. The correct sequence is: cast skill → wait for queue window → input light attack → cast next skill on GCD. The tempo is two inputs per second (light attack + skill), not fast button mashing. Mashing too quickly causes the skill to queue over the light attack, canceling it. Consistency matters more than speed — practice with a metronome at 60 BPM to build the rhythm.', 'verified'),

('mechanic', 'Weave Ratio and Light Attack Importance', 'A good weave ratio is 0.9+ light attacks per ability cast. Missing light attacks is one of the largest DPS losses because light attacks proc weapon enchantments, set effects (like Threads of War and Advancing Yokeda), and mythic effects (like Shattered Path Signant). In builds that rely on status effect procs, every missed light attack means fewer proc opportunities, which compounds into significant DPS loss over time.', 'verified'),

('mechanic', 'Static vs Dynamic Rotations', 'A static rotation follows a fixed sequence of button presses that repeats. It is easier to learn but typically produces 5-10k less DPS than a dynamic rotation. A dynamic rotation tracks individual DoT timers and reapplies each ability exactly as it expires, filling gaps with spammables. Dynamic rotations require more game knowledge and timer awareness but achieve higher uptime and fewer wasted casts. For learning, start static and transition to dynamic as comfort grows.', 'verified'),

('mechanic', 'Penetration Cap in ESO', 'All enemies in 4-player and 12-player content have 18,200 armor. The penetration cap matches this value — any penetration above 18,200 is wasted. Solo enemies range from 9,100 to 18,200. In group content, penetration should primarily come from support players (tanks/healers providing Major Breach at 5,948, Minor Breach at 2,974, Crusher enchant at ~2,740). DPS players typically only need the passive CP star Piercing (~700 pen). If under cap, common DPS sources are: one Light Armor piece for Concentration passive (939 pen), a monster set penetration line (~1,500), or the CP slottable Force of Nature.', 'verified'),

('mechanic', 'Critical Damage Cap in ESO', 'Critical strikes deal 50% bonus damage at base. The critical damage cap is 125% bonus damage — anything above is wasted. Sources for DPS to reach cap: Velothi mythic or Barbed Trap for Minor Force (10%), Medium Armor Dexterity passive (2% per piece, typically 12-14%), Herald of the Tome Faded Fortune passive (12%), Assassination Hemorrhage passive (10%). CP slottables Fighting Finesse or Backstabber can fill remaining gaps. In solo/4-player content where group buffs are limited, Khajiit race and Shadow mundus become more valuable for reaching the cap.', 'verified'),

('mechanic', 'Major and Minor Buff System', 'Buffs in ESO come in Major and Minor variants. You cannot stack two sources of the same Major buff, but you can have both Major and Minor active simultaneously. Key DPS buffs: Major Sorcery/Brutality (weapon/spell damage) — ideally from a support DK running Igneous Weapons, otherwise from potions or class skills. Major Prophecy/Savagery (crit chance) — from class abilities like Flames of Oblivion, Detonating Siphon, or Camouflaged Hunter. Minor Force (crit damage) — from Velothi mythic or Barbed Trap. Minor Slayer — from trial set 3-piece bonus, should always be active.', 'verified'),

-- ─── DPS Build Optimization ─────────────────────────────────────────────────

('build', 'Race Selection for DPS', 'Race has a small but measurable impact on DPS. Dark Elf is the strongest overall choice — competitive damage with both max stamina and magicka for flexibility. High Elf ties Dark Elf for magicka builds with slightly more max magicka (+100). Khajiit provides critical damage bonus, which is most valuable in solo content, 4-player groups, or casual raid environments where buffs are not fully optimized. For newer players, Khajiit is often the best recommendation. Any race can clear all content — the difference between best and worst race is roughly 3-4%.', 'community'),

('build', 'Mundus Stone for DPS', 'The Thief (critical chance) is the strongest mundus stone in 95% of situations for DPS. Shadow (critical damage) and Lover (penetration) can technically be argued in very specific optimized setups, but if configured incorrectly the damage loss is significant. Default to Thief unless you have a specific, calculated reason not to.', 'community'),

('build', 'Attribute Allocation for DPS', 'Put all 64 attribute points into one resource — either all Stamina or all Magicka depending on the build. Keeping all points in one stat gives the strongest damage scaling. Splitting points between resources lowers overall DPS. Your primary resource determines which spammables and class skills scale best.', 'community'),

('build', 'Food and Drink for DPS', 'Blue bi-stat food (max primary stat + max health) is recommended for most situations — only ~1% less DPS than pure stat food but adds ~5,400 health for survivability. Green single-stat food gives the absolute maximum damage but is marginal. For builds with sustain issues (especially mag-heavy rotations on stam builds), Candied Jesters Coins (primary stat + off-resource recovery) trades ~1-2% DPS for much easier sustain. Tri-stat food like Bewitched Sugar Skulls is for hybrid or mixed builds.', 'community'),

('build', 'Potions for DPS', 'Heroism potions are the strongest DPS option — they provide minor heroism for extra ultimate generation and are essential for builds using ultimate-scaling mythics like Shattered Path Signant. However, they are extremely expensive (Dragon Rheum + Dragons Blood + Columbine). Tri-stat potions (Columbine + Bugloss + Mountain Flower) are the practical alternative for sustain. Use Spell/Weapon Power potions only if you lack Major Sorcery/Brutality from other sources.', 'community'),

('build', 'Traits and Enchants for DPS', 'For standard DPS: Divines trait on all body pieces with max primary stat enchants. Bloodthirsty on all jewelry with Weapon Damage enchants. For weapons, common setups vary by build type. Charged weapons are used for status-effect-heavy builds (especially with Threads of War). Nirnhoned front bar is standard for many content builds. Infused back bar greatsword with Weapon Damage enchant is common for Maelstrom greatsword setups. Double Charged daggers with elemental enchants are used for status effect parsing builds.', 'community'),

('build', 'Champion Points for DPS', 'Blue (damage) tree: Master at Arms, Deadly Aim, Wrathful Strikes, and Exploiter are the standard 4 slottables. Exploiter is strongest with consistent off-balance uptime (coordinated groups) — swap to Fighting Finesse in casual content. Red (survival) tree: Boundless Vitality, Expert Evasion, Celerity, and Rejuvenation. Celerity helps reposition faster, Expert Evasion gives a free dodge roll for mechanics. Boundless Vitality is slightly stronger than Fortified.', 'community'),

-- ─── Meta DPS Builds ────────────────────────────────────────────────────────

('build', 'Runeblades Meta DPS Build (DK Base)', 'The current highest DPS setup in ESO uses Escalating Runeblades with Flame Lash on a Dragonknight base class. It pushes close to 190k DPS on dummy. Core mechanic: consuming Power Lash stacks (from hitting off-balance enemies with Flame Lash) grants 14% increased damage done to monsters for 45 seconds. This only works on DK base class characters. The build uses a priority spammable system: Flame Lash proc when available, Runeblades as filler, Tentacular Dread at 3 Crux for the 11% Abyssal Ink debuff. Gear: Perfected Null Arca + Advancing Yokeda + Huntsmans War Mask + Maelstrom Greatsword. Advancing Yokeda requires constant front-bar light attacks — never cast more than 3 back-bar abilities before returning to front bar.', 'community'),

('build', 'Warden Status Effect DPS Build', 'A Warden base class build using the Shattered Path Signant mythic achieves 180k+ DPS through status effect scaling. The mythic increases status effect damage by 1% per ultimate point (up to 170%). Combined with the Warden Glacial Presence passive (+250% chilled chance, +105% chilled damage) and Piercing Cold (+15% frost damage), Chilled alone contributes ~27k DPS. The build never casts Wild Guardian ultimate — the bear deals passive damage while maintaining maximum mythic value. Total status effect DPS: 60-70k before abilities. Gear: Shattered Path Signant + Threads of War + Null Arca + Maelstrom Greatsword. Requires Candied Jesters Coins food for mag sustain when parsing.', 'community'),

('build', 'Beam Build Overview', 'Beam builds (Fatecarver-based) use Herald of the Tome channeled abilities as the primary damage source. They offer strong cleave damage, easier execution, and extra survivability from Pragmatic Shield. While runeblades setups push higher raw DPS numbers, beam builds are still recommended for trifecta progression content because the survivability advantage and sufficient damage output make them safer. A Warden beam build can be converted to Sorcerer by swapping Winters Revenge + Arctic Wind for Hurricane + Liquid Lightning.', 'community'),

-- ─── DPS Gear Knowledge ─────────────────────────────────────────────────────

('gear', 'Trial Sets and Minor Slayer', 'Minor Slayer is a unique buff that only comes from trial set 3-piece bonuses. It should always be active in any DPS build — even unperfected sets from normal trials provide this buff. Current strong trial sets include Perfected Null Arca (burst damage procs on cooldown) and Slivers of Null Arca. Getting a trial set should be an early gearing goal for any DPS player.', 'community'),

('gear', 'Key DPS Gear Sets', 'Advancing Yokeda: +986 critical chance per melee light attack, stacking to 5. Front-bar only, stacks drop after 5 seconds without a light attack. Very strong but demands clean weaving. Threads of War: 100% increased status effect chance on light attacks. Core set for status-effect builds. Aegis Caller: summons a lesser Aegis on critical damage dealing massive AoE. Strong cleave alternative to Advancing Yokeda. Heartland Conqueror: crafted set, strong alternative for status effect builds. Huntsmans War Mask: requires bashing once every 60 seconds to maintain buff.', 'community'),

('gear', 'Velothi Mythic and Pale Order', 'Velothi Amulet provides Minor Force (10% critical damage) passively, freeing up a skill slot that would otherwise need Barbed Trap. It is the recommended mythic for most group DPS builds. Ring of the Pale Order provides significant self-healing from damage dealt and is the go-to mythic for solo content. Do not use Oakensoul for group content — it restricts you to one bar and severely limits DPS potential.', 'community'),

('gear', 'Maelstrom Greatsword', 'The Perfected Maelstrom Greatsword increases direct damage done by 12% for 18 seconds when casting Stampede. Since most DPS builds deal primarily direct damage, this is an extremely impactful buff. Stampede placement in the rotation matters — cast it so the 18-second buff covers your highest-damage window (spammable phase and burst window).', 'community'),

-- ─── Trash vs Boss DPS ──────────────────────────────────────────────────────

('build', 'Trash Mob vs Boss Gear Swapping', 'Optimized DPS players swap gear between trash packs and boss fights. Trash setup: burst-oriented sets like Tide-Born or Sul-Xan with Maelstrom Fire Staff back bar. Swap in skills like Proximity Detonation, Soul Burst, or Ulfsilds for pre-buffing and burst AoE. Ulfsilds is preferred over Soul Burst because it can be pre-buffed. Boss setup: standard single-target gear with sustained damage sets. The workflow is: pre-buff, drop Wall of Elements, bar swap, beam/spam.', 'community'),

('build', 'Anti-Cavalry Caltrops vs Razor Caltrops', 'Anti-Cavalry Caltrops is the default morph for group PvE content — it provides Major Breach to enemies in the area. Razor Caltrops is only used in solo content where you need the extra personal damage and there is no other source of Major Breach.', 'community'),

-- ─── Subclassing System ─────────────────────────────────────────────────────

('mechanic', 'Subclassing and Multi-Classing', 'ESOs subclassing system allows any character to use one skill tree from another class. Your base class (the class you created the character as) determines which class-specific interactions work — for example, Flame Lash power lash stacks only grant the 14% damage buff on DK base characters. You do not need to create a new character to use another class skill line — you level it through the subclassing system. Current meta subclass combinations for DPS include Assassination (from Nightblade) for Hemorrhage passive and Merciless Resolve, and Herald of the Tome (from Arcanist) for Runeblades and Faded Fortune.', 'community'),

-- ─── Dummy Parsing Context ──────────────────────────────────────────────────

('mechanic', 'Dummy Parsing Purpose and Context', 'The 21-million health trial dummy provides all group buffs, making it an unrealistic but standardized measurement tool. The value of parsing is not the number itself — it is building muscle memory for your rotation so you can execute while handling mechanics. Raid leaders primarily look at in-raid logs over dummy parses. Sustain is harder on dummy than in real content because group synergies help with resource return. Benchmark reference: 40k is beginner level, 100k is achievable with ~10 hours of practice and proper understanding, 140k+ is high-end, 180k+ is competitive meta.', 'community'),

('mechanic', 'Debuff Uptime Measurement', 'In fights with variable uptime (mobile bosses, intermission phases), measure debuff quality relative to a 100% uptime buff like Major Breach. If Major Breach shows 69% uptime on a given fight, and your Alkosh or other debuff shows 65%, that is excellent relative uptime. This method accounts for fight-specific downtime that affects all abilities equally.', 'community');
