-- Update Runeblades build doc with detailed off-balance / Power Lash mechanics

UPDATE knowledge_docs
SET content = 'The current highest DPS setup in ESO uses Escalating Runeblades with Flame Lash on a Dragonknight base class. It pushes close to 190k DPS on dummy. Core mechanic: hitting an off-balance enemy with Flame Lash grants 5 stacks of Power Lash for 20 seconds (20-second cooldown). Each Power Lash cast deals AoE Flame Damage and heals. Consuming ALL 5 stacks as a DK grants 7% increased damage done (14% against monsters) for 45 seconds — this buff is the reason the build is top-tier. You must consume all 5 stacks to trigger the buff; partial consumption grants nothing. Off-balance sources in trials: tanks using Crushing enchant + Blockade of Elements, or coordinated group off-balance with Wall of Elements + Weakness to Elements. The build uses a priority spammable system: Flame Lash proc when available (always consume all 5 Power Lash stacks immediately), Runeblades as filler, Tentacular Dread at 3 Crux for the 11% Abyssal Ink debuff. Gear: Perfected Null Arca + Advancing Yokeda + Huntsmans War Mask + Maelstrom Greatsword. Advancing Yokeda requires constant front-bar light attacks — never cast more than 3 back-bar abilities before returning to front bar.'
WHERE title = 'Runeblades Meta DPS Build (DK Base)';

-- Add a dedicated off-balance mechanics doc
INSERT INTO knowledge_docs (doc_type, title, content, source) VALUES
('mechanic', 'Off-Balance Mechanic in Trials', 'Off-balance is a status effect that makes enemies vulnerable. In coordinated trial groups, tanks and supports maintain off-balance uptime through Wall of Elements (lightning staff), Crushing enchant procs, and specific set bonuses. When an enemy is off-balance, DK players using Flame Lash gain 5 stacks of Power Lash — consuming all 5 stacks grants 7% damage done (14% vs monsters) for 45 seconds. This is the core damage amplifier for the Runeblades meta build. Off-balance has a 7-second cooldown after being consumed or expiring. Coordinating off-balance uptime is one of the most impactful things a trial group can do for DK DPS players. The CP slottable Exploiter increases damage against off-balance targets and becomes very strong in groups with coordinated off-balance.', 'verified');
