-- Fix Flame Lash / Power Lash mechanics to match Update 49 (March 2026) patch notes
-- Previous version incorrectly stated 7% (14% vs monsters). Correct is 14% damage done, halved vs players.
-- Also clarifies the off-balance window mechanic: stacks are used DURING the off-balance window.

UPDATE knowledge_docs
SET content = 'The current highest DPS setup in ESO uses Escalating Runeblades with Flame Lash on a Dragonknight base class. It pushes close to 190k DPS on dummy. Core mechanic (Update 49): when Flame Lash hits an off-balance enemy, it becomes Power Lash for 7.9 seconds, generating 5 stacks. Power Lash costs 50% less, deals 40% more damage, and hits in a 5-meter AoE. You must consume ALL 5 stacks during the off-balance window — doing so grants 14% increased damage done (halved against players) for 45 seconds as a Dragonknight. This buff is the reason the build is top-tier. The off-balance trigger has a 20-second cooldown, so rotation timing around off-balance windows is critical. Off-balance sources in trials: tanks using Crusher enchant + Wall of Elements (lightning staff), or coordinated group off-balance. The build uses a priority spammable system: when boss goes off-balance, immediately spam Power Lash to consume all 5 stacks, then use Runeblades as filler, and Tentacular Dread at 3 Crux for the 11% Abyssal Ink debuff. Flame Lash also heals on every hit (not just Power Lash) as of Update 49. Gear: Perfected Null Arca + Advancing Yokeda + Huntsmans War Mask + Maelstrom Greatsword. Advancing Yokeda requires constant front-bar light attacks — never cast more than 3 back-bar abilities before returning to front bar.'
WHERE title = 'Runeblades Meta DPS Build (DK Base)';

UPDATE knowledge_docs
SET content = 'Off-balance is a status effect that makes enemies vulnerable to specific class mechanics. In coordinated trial groups, tanks and supports maintain off-balance uptime through Wall of Elements (lightning staff), Crusher enchant procs, and specific set bonuses. Off-balance has a 7-second cooldown after being consumed or expiring. For DK players using Flame Lash: when Flame Lash hits an off-balance enemy, it becomes Power Lash for 7.9 seconds with 5 stacks. Each Power Lash cast costs 50% less, deals 40% more AoE damage, and heals. Consuming all 5 stacks grants 14% damage done for 45 seconds (DK only). The off-balance trigger has a 20-second cooldown — rotation timing around these windows is the most important skill for DK DPS in trials. The CP slottable Exploiter increases damage against off-balance targets and becomes very strong in groups with coordinated off-balance uptime.'
WHERE title = 'Off-Balance Mechanic in Trials';
