-- Enrich knowledge base with verified mentor advice from AEDRA and TGC Discord channels
-- Sources: dps-aera.txt (AEDRA guild), dps-tgc.txt (TGC guild, Madmaxx727 Certified Mentor)
-- Only text-stated facts included; screenshot-referenced builds excluded.

-- Update beam build doc with trait details and ult usage from TGC mentors
UPDATE knowledge_docs
SET content = 'Beam builds (Fatecarver-based) use Herald of the Tome channeled abilities as the primary damage source. They offer strong cleave damage, easier execution, and extra survivability from Pragmatic Shield. While runeblades setups push higher raw DPS numbers, beam builds are recommended for trifecta progression and beginner vet trial content because the survivability advantage makes them safer. Beam builds are the most recommended entry point for new DPS players in vet trials. Traits: Double Charged for dummy parsing, Nirnhoned front bar + Charged back bar in actual content. Ultimates: use Incapacitating Strike as your default ult (only 70 cost). Languid Eye or Standard of Might is only cast once as an opener, then Incap for the rest of the fight. A Warden beam build can be converted to Sorcerer by swapping Winters Revenge + Arctic Wind for Hurricane + Liquid Lightning. Keep Storm Calling as your base Sorcerer skill line.'
WHERE id = 58;

-- Add Earthen vs Winter's set comparison from MrLongo (Tier 9 DD / Scorepusher)
INSERT INTO knowledge_docs (doc_type, title, content, source) VALUES
('gear', 'Earthen vs Winters Respite Set Comparison', 'Earthen Heart and Winters Respite are close in single-target DPS once you account for crit RNG and performance. Earthen is better for single-target and cleave because Frost Weapon (from Winters) can proc on the wrong target in add-heavy fights. Earthen also has a crit damage passive that helps in fights where group crit damage average is poor. Winters has a 10-second DOT on the back bar which makes the rotation slightly more complex. Earthen rotation is easier without the extra back-bar DOT, giving more time for beaming. For content, drop the Frost enchant from Winters and use Weapon/Spell Damage enchant instead — the extra damage for cleave outweighs the single-target Chilled proc.', 'verified');

-- Add beginner gear progression advice from TGC Certified Mentors
INSERT INTO knowledge_docs (doc_type, title, content, source) VALUES
('build', 'Beginner DPS Gear Progression', 'For new DPS players entering vet trials, focus on this progression: 1) Farm Velothi mythic for group content — it is the single highest-impact item for DPS. 2) Get Ring of the Pale Order for solo content and overland farming. 3) Do not bother with OakenSoul — it is a crutch that teaches bad habits and caps your potential. 4) Start with unperfected trial sets from normal trials to get Minor Slayer active (any 3-piece trial set bonus). 5) Farm perfected versions later from vet trials. 6) Beam builds (Fatecarver-based) are the recommended starting point for vet trial DPS — they are easier to execute and have built-in survivability. 7) The Runeblades + Flame Lash meta build is stronger but requires complex off-balance timing that is not beginner-friendly.', 'verified');

-- Add recommended builds by experience level
INSERT INTO knowledge_docs (doc_type, title, content, source) VALUES
('build', 'Recommended DPS Builds by Experience Level', 'Beginner (first vet trials): Beam build (Fatecarver) on any class — easiest rotation, strong cleave, built-in survivability from Pragmatic Shield. Sorcerer base is particularly beginner-friendly due to pet healing and Critical Surge. Intermediate (farming vet trials, working on trifectas): Beam build with optimized gear (Perfected trial sets, Velothi, proper traits). Start learning trash-to-boss gear swapping. Advanced (trifecta progging, score pushing): Escalating Runeblades + Flame Lash on Dragonknight base — highest DPS ceiling (~190k on dummy) but requires mastery of off-balance timing, Power Lash stack management, and Advancing Yokeda front-bar uptime. All builds at every level should use subclassing: Assassination (from Nightblade) for Hemorrhage passive and Merciless Resolve is standard on all DPS builds.', 'verified');

-- Add ult usage guide from TGC mentor discussions
INSERT INTO knowledge_docs (doc_type, title, content, source) VALUES
('mechanic', 'Ultimate Usage for DPS', 'Incapacitating Strike (Assassination/Nightblade subclass) is the default DPS ultimate at only 70 cost — use it on cooldown for the rest of the fight after your opener. Opener ult: cast your back-bar ultimate once at the start of the fight (Standard of Might for DK, Languid Eye for beam builds, etc.) then switch to Incap for all subsequent ult casts. Standard of Might / Languid Eye are strong for the first off-balance burst window but less effective after that. Even the current meta DK Runeblades builds only cast Standard once at the start. The 70-cost Incap generates more total damage over a fight than saving for expensive ults.', 'verified');

-- Essential addons guide from TGC channel description (Engineer_Karl / TGC staff)
INSERT INTO knowledge_docs (doc_type, title, content, source) VALUES
('mechanic', 'Essential Addons for Trials', 'Combat addons (install these first): Raid Notifier — trial mechanic notifications, essential even for beginner content. Combat Metrics — measures DPS on the 21M health trial dummy. Codes Combat Alerts — tells you when to block or dodge roll. GCD Bar — visual aid for perfect light attack weaving. Hodor Reflexes — group ultimate, DPS, and status icon sharing. Untaunted — aggro loss detection for tanks. Samurai — Raid Notifier supplement. QOL addons (highly recommended): Bandits User Interface — comprehensive UI overhaul. BeamMeUp — free travel to random wayshrines. Item Set Browser — look up sets in-game without alt-tabbing. Personal Assistant — automates repair, recharge, loot, banking. Map Pins — shows skyshards, lorebooks, and points of interest. Dungeon Tracker — fast-queue for dungeons with missing skill points. Set uptime trackers: Roaring Opportunist Tracker, Turning Tide Tracker, Archdruid Devyric Tracker, and Martial Knowledge Tracker help maintain buff uptimes on support sets.', 'verified');

-- Buff uptime evaluation technique from Yas (DPS, AEDRA guild)
INSERT INTO knowledge_docs (doc_type, title, content, source) VALUES
('mechanic', 'Evaluating Buff Uptime in Trials', 'To accurately evaluate buff uptimes on bosses with movement or downtime phases (like Xalaka), compare the uptime of the buff you are tracking against a buff that should theoretically be 100% — like Major Breach. If Major Breach shows 69% uptime on Xalaka (due to boss movement and phase transitions), then an Alkosh uptime of 65% on that same fight represents excellent uptime relative to what is possible. Do not compare raw uptime percentages across different fights — a 65% Alkosh uptime on a movement-heavy fight like Xalaka may be better than 80% on a static fight. Use Combat Metrics (CMX) addon to view these uptimes after each fight.', 'verified');

-- Update dummy parsing doc with raid lead perspective from AEDRA
UPDATE knowledge_docs
SET content = 'The 21-million health trial dummy provides all group buffs, making it an unrealistic but standardized measurement tool. The value of parsing is not the number itself — it is building muscle memory for your rotation so you can execute while handling mechanics. Raid leaders primarily look at in-raid logs over dummy parses — if you can show good damage on a fight like Taleria, raid leads will let you into harder progression groups regardless of your dummy parse. Once you have vet trial clears, parse numbers become meaningless for getting rostered. Sustain is harder on dummy than in real content because group synergies help with resource return. Benchmark reference: 40k is beginner level, 100k is achievable with proper understanding, 140k+ is high-end, 180k+ is competitive meta. Never chase a dummy number as a goal — use it to refine your rotation, then prove yourself in actual trials.'
WHERE title = 'Dummy Parsing Purpose and Context';

-- Update trash mob doc with more specific skill details from TGC mentors
UPDATE knowledge_docs
SET content = 'Optimized DPS players swap gear between trash packs and boss fights. Trash setup: burst-oriented sets like Tide-Born or Sul-Xan with Maelstrom Fire Staff back bar. Swap in skills like Proximity Detonation, Soul Burst, or Ulfsilds for pre-buffing and burst AoE. Ulfsilds is preferred over Soul Burst because it can be pre-buffed and magicka sustain is less of a concern for short trash fights. Boss setup: standard single-target gear with sustained damage sets. The trash rotation workflow: pre-buff with Ulfsilds or Soul Burst, drop Wall of Elements, bar swap, then beam or spam. Two-handed weapons also work well for trash. Anti-Cavalry Caltrops is the default morph for trash (provides Major Breach to enemies in area). Fulminating Rune is a fine default skill — swap to Barbed Trap or something else situationally if you struggle with sustain.'
WHERE title = 'Trash Mob vs Boss Gear Swapping';
