/**
 * Item Icon Resolver
 *
 * Resolves ESO item icons using a pre-fetched local JSON file
 * (generated by scripts/fetch-item-icons.mjs) containing 154K+ item→icon
 * mappings from UESP's minedItemSummary table. Zero runtime API calls
 * needed for any item in the local data.
 *
 * Falls back to the UESP API for items not in the local data (e.g., new
 * items added after the last data refresh).
 *
 * CDN: https://esoicons.uesp.net/esoui/art/icons/{iconName}.png
 *
 * To refresh the local data:
 *   node scripts/fetch-item-icons.mjs
 */

import { Logger } from '@/utils/logger';

// Pre-fetched icon data: { icons: string[], items: Record<string, number> }
import iconData from '../data/itemIcons.json';
import { getItemInfo } from '../data/itemIdMap';
import type { SlotType } from '../data/slotTypes';

const logger = new Logger({ contextPrefix: 'ItemIconResolver' });

/** Base URL for the UESP icon CDN */
const UESP_ICON_CDN = 'https://esoicons.uesp.net';

/** Base URL for the UESP item data API (fallback only) */
const UESP_API = 'https://esolog.uesp.net/exportJson.php';

/** Runtime cache for items resolved via API fallback */
const fallbackCache = new Map<number, string | null>();

/** Pending fetch promises so we don't start duplicate requests */
const pendingFetches = new Map<number, Promise<string | null>>();

/**
 * Build a CDN URL from an icon name.
 *   "gear_undnarlimor_head_a" → "https://esoicons.uesp.net/esoui/art/icons/gear_undnarlimor_head_a.png"
 */
function iconNameToUrl(iconName: string): string {
  return `${UESP_ICON_CDN}/esoui/art/icons/${iconName}.png`;
}

/**
 * Look up an item's icon URL from the local pre-fetched data.
 * Returns a CDN URL, or null if the item isn't in the local data.
 */
function lookupLocal(itemId: number): string | null {
  const iconName = lookupIconName(itemId);
  return iconName ? iconNameToUrl(iconName) : null;
}

/** Look up the raw icon filename (without CDN prefix or extension) from local data. */
function lookupIconName(itemId: number): string | null {
  const typedData = iconData as { icons: string[]; items: Record<string, number> };
  const index = typedData.items[String(itemId)];
  if (index === undefined) return null;
  return typedData.icons[index] ?? null;
}

/**
 * UESP gear-icon tokens → ESO weapon type labels.
 * Derived from icon filenames like `gear_argonian_1hsword_d`. The icon is the
 * only per-item weapon-type signal available — itemIdMap only tags the slot
 * (`weapon` / `offhand`), not the specific weapon. Staff icons don't
 * distinguish fire/frost/lightning/resto, so they map to a generic "Staff".
 */
const WEAPON_ICON_TOKEN_LABELS: Record<string, string> = {
  '1haxe': 'Axe',
  '1hsword': 'Sword',
  '1hhammer': 'Mace',
  '1hmace': 'Mace',
  '1hammer': 'Mace',
  '1hhamer': 'Mace',
  '1hdagger': 'Dagger',
  '2haxe': 'Battle Axe',
  '2hsword': 'Greatsword',
  '2hhammer': 'Maul',
  '2hmace': 'Maul',
  dagger: 'Dagger',
  bow: 'Bow',
  staff: 'Staff',
  shield: 'Shield',
};

const WEAPON_ICON_TOKEN_RE = new RegExp(
  `_(${Object.keys(WEAPON_ICON_TOKEN_LABELS).join('|')})(?:_|$)`,
);

/**
 * Derive the specific weapon-type label (e.g. "Sword", "Dagger", "Bow") from
 * an already-resolved icon URL. Pure parser over the URL's filename so the
 * label stays in lockstep with whatever icon the caller decided to render —
 * including the async UESP fallback path and the page-level `resolvedIconId`
 * correction for generic/slot-mismatched item IDs. Returns null when the URL
 * doesn't match the UESP CDN shape or its icon token isn't a weapon.
 */
export function parseWeaponTypeFromIconUrl(url: string | null | undefined): string | null {
  if (!url) return null;
  const fileMatch = url.match(/\/icons\/([^/?#]+)\.png(?:[?#]|$)/i);
  if (!fileMatch) return null;
  const tokenMatch = fileMatch[1].match(WEAPON_ICON_TOKEN_RE);
  return tokenMatch ? (WEAPON_ICON_TOKEN_LABELS[tokenMatch[1]] ?? null) : null;
}

/**
 * Two-handed weapon labels per ESO equip rules: these occupy BOTH main-hand
 * AND off-hand slots, so a second weapon (or shield) can't coexist with them
 * on the same bar. Staves collapse to "Staff" here because icons don't
 * distinguish Inferno/Frost/Lightning/Restoration — all four are 2H anyway,
 * so the distinction doesn't matter for slot gating.
 *
 * Source: UESP Online:Weapons — Two-handed weapons include Greatswords,
 * Battle Axes, Mauls; Bows; all Staves.
 */
const TWO_HANDED_WEAPON_LABELS = new Set<string>([
  'Battle Axe',
  'Greatsword',
  'Maul',
  'Bow',
  'Staff',
]);

/**
 * True when the itemId is a slot-specific weapon whose icon classifies as
 * a two-handed type (Greatsword / Battle Axe / Maul / Bow / Staff).
 *
 * IMPORTANT slot-specificity guard: generic LibSets IDs (e.g. 685 =
 * "Bloodthorn's Touch Gear", no `slot` field) collide with unrelated
 * entries in UESP's icon database — `getItemIconUrl(685)` returns
 * `gear_breton_staff_d`. Treating that as a 2H match would false-positive
 * lock and auto-clear the off-hand for imported/legacy loadouts that
 * carry generic IDs. Only classify when the stored itemId's own metadata
 * says it's a weapon/offhand slot item.
 *
 * Synchronous — reads only the pre-fetched local data + the already-warmed
 * fallback cache. Returns `false` when the icon isn't resolvable yet;
 * callers relying on this for equip-rule enforcement must pair it with an
 * async recompute (see `fetchIsTwoHandedWeapon`) so newly-added items and
 * rehydrated gear configs don't silently skip the gate on first render.
 *
 * Preferred over name-keyword checks (`name.includes('greatsword')`),
 * which never match because itemIdMap stores generic names like
 * "<Set> Weapon".
 */
export function isTwoHandedWeapon(itemId: number | null | undefined): boolean {
  if (!itemId || itemId <= 0) return false;
  const info = getItemInfo(itemId);
  if (info?.slot !== 'weapon' && info?.slot !== 'offhand') return false;
  const url = getItemIconUrl(itemId);
  const label = parseWeaponTypeFromIconUrl(url);
  return label !== null && TWO_HANDED_WEAPON_LABELS.has(label);
}

/**
 * Async counterpart to `isTwoHandedWeapon` — triggers the UESP fallback
 * fetch for items that aren't in local data yet, so equip-rule enforcement
 * doesn't silently fail on newly-added weapons. Use this when gating the
 * off-hand slot; sync `isTwoHandedWeapon` is fine for cosmetic indicators
 * that can afford to re-render once the icon lands.
 *
 * Applies the same slot-specificity guard as the sync variant — see
 * `isTwoHandedWeapon` for why generic set IDs must be rejected before
 * icon classification.
 */
export async function fetchIsTwoHandedWeapon(itemId: number | null | undefined): Promise<boolean> {
  if (!itemId || itemId <= 0) return false;
  const info = getItemInfo(itemId);
  if (info?.slot !== 'weapon' && info?.slot !== 'offhand') return false;
  const url = await fetchItemIconUrl(itemId);
  const label = parseWeaponTypeFromIconUrl(url);
  return label !== null && TWO_HANDED_WEAPON_LABELS.has(label);
}

/**
 * Text-based 2H fallback for degraded gear records (imports with only a
 * stale `name` string, rehydrated state where the itemId no longer maps
 * to any known item). Uses whole-word regex so substrings like "elbow"
 * don't false-match the `bow` token.
 *
 * Intentionally LAST-RESORT — callers should always prefer
 * `isTwoHandedWeapon`/`fetchIsTwoHandedWeapon` on the canonical item ID
 * first. Scope checks to the item's own display name, not the set name,
 * because set names like "Bow of the Wild Hunt" would false-positive.
 */
const TWO_HANDED_NAME_RE = /\b(greatsword|battle\s?axe|maul|bow|staff)\b/i;

export function isTwoHandedFromName(text: string | null | undefined): boolean {
  if (!text) return false;
  return TWO_HANDED_NAME_RE.test(text);
}

/**
 * Generic slot-name suffixes that itemIdMap uses when a specific weapon-type
 * name isn't available. Callers strip the trailing match and splice in a
 * specific type (Sword/Dagger/Bow/…) once the icon is resolved.
 *
 * Order matters — longer/more-specific suffixes (" Off-Hand") must come
 * before shorter overlaps (" Hand") would if we ever added them.
 */
export const GENERIC_WEAPON_SUFFIXES = [' Weapon', ' Off-Hand', ' Offhand', ' Gear'] as const;

/**
 * Replace a generic slot-name suffix on an item name with the specific weapon
 * type parsed from its icon URL. No-ops when the slot isn't a weapon slot,
 * when the icon URL doesn't expose a weapon token, or when the raw name
 * doesn't end in a recognized generic suffix.
 *
 * The `slotType` gate intentionally uses the SLOT POSITION (weapon / offhand)
 * rather than the item's own `slot` tag, so generic set IDs (e.g. 2558 =
 * "Mother's Sorrow Gear") still get a specific label once the caller has
 * corrected the icon to a concrete slot-specific item.
 */
export function applyWeaponTypeToName(
  rawName: string,
  iconUrl: string | null | undefined,
  slotType: SlotType | undefined,
): string {
  const isWeaponSlot = slotType === 'weapon' || slotType === 'offhand';
  if (!isWeaponSlot) return rawName;
  const weaponType = parseWeaponTypeFromIconUrl(iconUrl);
  if (!weaponType) return rawName;
  const suffix = GENERIC_WEAPON_SUFFIXES.find((s) => rawName.endsWith(s));
  if (!suffix) return rawName;
  return rawName.slice(0, -suffix.length) + ' ' + weaponType;
}

/**
 * Resolve an item's display name for a given slot — the single callable
 * used by the /bv, /rv, build-editor, and loadout-manager UIs so they all
 * agree on how to render weapon labels.
 *
 * Synchronous: reads `getItemInfo` + local icon data. Callers that already
 * track an async-resolved icon URL (e.g. BuildViewPage's `iconUrl` state
 * from `fetchItemIconUrl`) should pass it via `iconUrlOverride` so the
 * label follows whatever icon they're rendering.
 *
 * SAFETY GUARD: only derives a specific weapon type when the STORED itemId
 * uniquely identifies one (itemInfo.slot is 'weapon' or 'offhand'). For
 * generic set IDs with no slot field, the caller's icon is commonly a
 * `getSetItemsBySlot(...)[0]` fallback — an arbitrary variant of the set.
 * Asserting a weapon type from that would silently lie about the user's
 * actual chosen weapon in shared/read-only views. Generic items keep their
 * generic label regardless of what icon is rendered.
 */
export function deriveItemNameForSlot(
  itemId: number | null | undefined,
  slotType: SlotType | undefined,
  iconUrlOverride?: string | null,
): string {
  const id = itemId ?? 0;
  const info = id > 0 ? getItemInfo(id) : undefined;
  const rawName = info?.name ?? `Item #${id || '?'}`;
  const itemIsSlotSpecificWeapon = info?.slot === 'weapon' || info?.slot === 'offhand';
  if (!itemIsSlotSpecificWeapon) return rawName;
  const url = iconUrlOverride !== undefined ? iconUrlOverride : getItemIconUrl(id);
  return applyWeaponTypeToName(rawName, url, slotType);
}

/**
 * Fetch the icon URL for a single item from UESP (fallback).
 * Only called for items not present in the local JSON data.
 */
async function fetchIconFromUESP(itemId: number): Promise<string | null> {
  try {
    const url = `${UESP_API}?table=minedItemSummary&id=${itemId}`;
    const response = await fetch(url);

    if (!response.ok) {
      logger.warn('UESP API returned non-OK status', { itemId, status: response.status });
      return null;
    }

    const data = await response.json();
    const item = (data.minedItemSummary as Array<{ icon?: string }>)?.[0];
    if (!item?.icon || typeof item.icon !== 'string') return null;
    if (item.icon.includes('icon_missing')) return null;

    // Convert DDS path → PNG CDN URL
    const match = item.icon.match(/([^/]+)\.dds$/i);
    return match ? iconNameToUrl(match[1]) : null;
  } catch (err) {
    logger.warn('Failed to fetch icon from UESP', {
      itemId,
      error: err instanceof Error ? err.message : String(err),
    });
    return null;
  }
}

/**
 * Get the icon URL for a given item ID (synchronous).
 *
 * Checks the local pre-fetched data first (instant), then
 * the runtime fallback cache. Returns null if not available locally
 * and no fallback result is cached yet.
 */
export function getItemIconUrl(itemId: number | null | undefined): string | null {
  if (!itemId || itemId <= 0) return null;

  // 1. Check local pre-fetched data (instant, ~154K items)
  const local = lookupLocal(itemId);
  if (local) return local;

  // 2. Check runtime fallback cache
  if (fallbackCache.has(itemId)) {
    return fallbackCache.get(itemId) ?? null;
  }

  return null;
}

/**
 * Async version: resolve an item's icon URL.
 *
 * Returns instantly from local data when possible, otherwise
 * falls back to a UESP API call (deduplicated).
 */
export async function fetchItemIconUrl(itemId: number): Promise<string | null> {
  if (itemId <= 0) return null;

  // 1. Check local pre-fetched data (instant)
  const local = lookupLocal(itemId);
  if (local) return local;

  // 2. Check runtime fallback cache
  if (fallbackCache.has(itemId)) {
    return fallbackCache.get(itemId) ?? null;
  }

  // 3. Join an existing in-flight fetch
  const pending = pendingFetches.get(itemId);
  if (pending) return pending;

  // 4. Fall back to UESP API for unknown items
  logger.info('Item not in local data, fetching from UESP', { itemId });
  const fetchPromise = fetchIconFromUESP(itemId).then((url) => {
    fallbackCache.set(itemId, url);
    pendingFetches.delete(itemId);
    return url;
  });

  pendingFetches.set(itemId, fetchPromise);
  return fetchPromise;
}

/**
 * Pre-populate results for a batch of item IDs.
 * Only makes API calls for items not already in the local data.
 */
export async function prefetchItemIcons(itemIds: number[]): Promise<void> {
  const needsFetch = itemIds.filter((id) => id > 0 && !lookupLocal(id) && !fallbackCache.has(id));

  const unique = [...new Set(needsFetch)];
  for (const id of unique) {
    await fetchItemIconUrl(id);
    await new Promise((r) => setTimeout(r, 50));
  }
}
