// Auto-generated version information
// This file is automatically generated during build - do not edit manually

export const VERSION_INFO = {
  version: "0.1.0",
  buildTime: "2025-09-09T06:09:33.547Z",
  gitCommit: "88df5acd2a2e4067f352dcf4984e689c5dcf0838",
  shortCommit: "88df5acd",
  buildId: "0.1.0-88df5acd-1757398173625",
  timestamp: 1757398173625,
  cacheBuster: "v=01088df5acd1757398173625",
} as const;

export const {
  version,
  buildTime,
  gitCommit,
  shortCommit,
  buildId,
  timestamp,
  cacheBuster,
} = VERSION_INFO;
