// Auto-generated version information
// This file is automatically generated during build - do not edit manually

export const VERSION_INFO = {
  version: '0.1.0',
  buildTime: '2025-09-10T04:59:01.504Z',
  gitCommit: 'ba262c5f0d9593a26f3f9981f1cc4fb964ddb00c',
  shortCommit: 'ba262c5f',
  buildId: '0.1.0-ba262c5f-1757480341540',
  timestamp: 1757480341540,
  cacheBuster: 'v=010ba262c5f1757480341540',
} as const;

export const { version, buildTime, gitCommit, shortCommit, buildId, timestamp, cacheBuster } =
  VERSION_INFO;
