import { chromium } from 'playwright';
import { resolve } from 'path';
const BASE = 'http://localhost:3000';
const OUT = resolve('.screenshots');
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.setViewportSize({ width: 1280, height: 900 });
await page.goto(`${BASE}/roster-hub`, { waitUntil: 'networkidle' });
await page.waitForTimeout(4000);
await page.screenshot({ path: `${OUT}/filterbar-close.png`, clip: { x: 0, y: 220, width: 1280, height: 160 } });
console.log('✓ filterbar-close.png');
await browser.close();
