name: 'Build and Deploy'
description: 'Build React app and Storybook, then deploy to GitHub Pages'
inputs:
  enable_sourcemaps:
    description: 'Enable source map generation'
    required: false
    default: 'false'
  release_version:
    description: 'Release version to set in environment'
    required: false
    default: ''
  github_token:
    description: 'GitHub token for deployment'
    required: true
outputs:
  deployment-url:
    description: 'URL where the site was deployed'
    value: ${{ steps.deployment.outputs.page_url }}
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Set release version
      if: inputs.release_version != ''
      shell: bash
      run: |
        echo "REACT_APP_VERSION=${{ inputs.release_version }}" >> $GITHUB_ENV

    - name: Setup Pages
      uses: actions/configure-pages@v5
      id: setup

    - name: Build project
      shell: bash
      run: |
        export GENERATE_SOURCEMAP=${{ inputs.enable_sourcemaps }}
        npm run build
      env:
        VITE_BASE_URL: '${{steps.setup.outputs.base_url}}'

    - name: Build Storybook
      shell: bash
      run: |
        REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
        export STORYBOOK_BASE_PATH="/$REPO_NAME/storybook/"
        npm run build-storybook

    - name: Move Storybook to build directory
      shell: bash
      run: |
        mkdir -p build/storybook
        cp -r storybook-static/* build/storybook/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./build
