/**
 * Static map of ESO gear set IDs to display names.
 *
 * Used by the decoder to show human-readable set names in Discord embeds
 * instead of raw numeric IDs. Sourced from the frontend's KnownSetIDs enum
 * and SET_DISPLAY_NAMES record.
 *
 * Update this map when new sets are added to the game.
 */

export const SET_NAMES: Record<number, string> = {
  // Support — Healer 5-piece
  147: 'Martial Knowledge',
  180: 'Powerful Assault',
  185: 'Spell Power Cure',
  194: 'Combat Physician',
  332: 'Master Architect',
  346: "Jorvuld's Guidance",
  391: 'Olorime',
  395: 'Perfected Olorime',
  455: "Zen's Redress",
  496: 'Roaring Opportunist',
  497: 'Perfected Roaring Opportunist',

  // Support — Tank 5-piece
  232: 'Alkosh',
  331: 'War Machine',
  446: 'Yolnahkriin',
  451: 'Perfected Yolnahkriin',
  571: "Drake's Rush",
  585: 'Saxhleel Champion',
  589: 'Perfected Saxhleel Champion',
  648: 'Pearlescent Ward',
  649: "Pillager's Profit",
  650: "Perfected Pillager's Profit",
  651: 'Perfected Pearlescent Ward',
  768: 'Lucent Echoes',
  771: 'Perfected Lucent Echoes',

  // Monster Sets
  163: 'Bloodspawn',
  164: 'Lord Warden',
  166: 'Engine Guardian',
  168: "Nerien'eth",
  169: 'Valkyn Skoria',
  170: 'Maw of the Infernal',
  183: 'Molag Kena',
  256: 'Mighty Chudan',
  257: 'Velidreth',
  266: "Kra'gh",
  267: 'Swarm Mother',
  269: 'Chokethorn',
  270: 'Slimecraw',
  273: 'Ilambris',
  274: 'Iceheart',
  275: 'Stormfist',
  276: 'Tremorscale',
  278: 'The Troll King',
  280: 'Grothdarr',
  341: 'Earthgore',
  350: 'Zaan',
  354: 'Mad Tinkerer',
  397: 'Balorgh',
  398: 'Vykosa',
  432: 'Stonekeeper',
  436: 'Symphony of Blades',
  458: 'Grundwulf',
  476: 'Grave Guardian',
  479: "Kjalnar's Nightmare",
  498: "Yandir's Might",
  534: 'Stone Husk',
  577: 'Encratis',
  578: 'Baron Zaudrus',
  602: 'Crimson Oath',
  609: 'Magma Incarnate',
  620: "Gryphon's Reprisal",
  627: 'Spaulder of Ruin',
  633: 'Nazaray',
  634: 'Nunatak',
  635: 'Lady Malygda',
  636: 'Baron Thirsk',
  666: 'Archdruid Devyric',
  683: 'Roksa the Warped',
  687: 'Ozezan',
  738: 'The Blind',
  828: 'Black Gem Monstrosity',

  // Mythics
  575: 'Pale Order',
  576: 'Pearls of Ehlnofey',
  593: 'Gaze of Sithis',
  594: "Harpooner's Wading Kilt",
  596: "Death Dealer's Fete",
  625: 'Markyn Ring of Majesty',
  654: "Mora's Whispers",
  657: "Sea-Serpent's Coil",
  658: 'Oakensoul Ring',
  691: 'Cryptcanon Vestments',
  694: "Velothi Ur-Mage's Amulet",

  // DPS 5-piece
  80: "Hunding's Rage",
  83: 'Elf Bane',
  98: 'Necropotence',
  127: 'Deadly Strike',
  137: 'Advancing Yokeda',
  157: 'Undaunted Unweaver',
  160: 'Burning Spellweave',
  172: 'Infallible Aether',
  207: 'Law of Julianos',
  212: 'Briarheart',
  292: "Mother's Sorrow",
  304: 'Medusa',
  320: 'War Maiden',
  336: 'Pillar of Nirn',
  353: 'Mechanical Acuity',
  369: 'Merciless Charge',
  389: 'Relequen',
  393: "Relequen's Perfected",
  394: "Siroria's Perfected",
  430: "Tzogvin's Warband",
  444: "False God's Devotion",
  449: "Perfected False God's",
  450: "Lokkestiiz's Perfected",
  456: 'Azureblight',
  470: 'New Moon Acolyte',
  495: "Vrol's Perfected",
  522: 'Perfected Merciless Charge',
  570: "Kinras's Wrath",
  586: "Sul-Xan's Torment",
  590: "Perfected Sul-Xan's Torment",
  591: "Perfected Bahsei's Mania",
  647: 'Coral Riptide',
  652: 'Perfected Coral Riptide',
  684: "Runecarver's Blaze",
  701: 'Peace and Serenity',
  702: "Ansuul's Torment",
  707: "Perfected Ansuul's Torment",
  758: 'Macabre Vintage',
  766: 'Mora Scribe',
  767: 'Slivers of the Null Arca',
  769: "Xoryn's Masterpiece",
  770: "Perfected Xoryn's Masterpiece",
  772: 'Perfected Slivers of the Null Arca',
  773: 'Perfected Mora Scribe',
  776: 'Pyrebrand',
  777: 'Corpseburster',
  779: 'Beacon of Oblivion',
  794: 'Vandorallen',
  795: 'Jerensi',
  809: 'Tide-Born Wildstalker',
  812: "Rakkhat's Voidmantle",
  815: "Kazpian's",
  820: "Perfected Kazpian's",
  825: 'Xanmeer Spellweaver',
  831: 'Coup De Grâce',

  // Arena Weapons
  314: "The Master's Mace",
  316: "The Master's Bow",
  317: "The Master's Ice Staff",
  318: "The Master's Restoration Staff",
  358: "Asylum's Perfected Dagger",
  362: "Asylum's Perfected Restoration Staff",
  372: "Maelstrom's Bow",
  373: 'Crushing Wall',
  392: "Galenwe's Perfected",
  413: 'Blackrose Prison Dagger',
  414: 'Blackrose Bow',
  415: 'Blackrose Ice Staff',
  416: 'Blackrose Resto',
  425: 'Blackrose Perfected Dagger',
  426: 'Blackrose Perfected Bow',
  427: 'Blackrose Perfected Ice Staff',
  428: 'Blackrose Perfected Resto',
  526: 'Perfected Crushing Wall',
  533: 'Perfected Grand Rejuvenation',
  559: "Vateshran's Greatsword",
  563: 'Vateshran Perfected Sword',
  564: 'Vateshran Perfected Dagger',
  567: "Vateshran's Perfected Staff",

  // Support — Additional 5-piece
  128: 'Blessing of the Potentates',
  138: 'Resilient Yokeda',
  184: 'Brands of Imperium',
  196: 'Leeching Plate',
  610: 'Wretched Vitality',
  614: "Hexos' Ward",
  622: 'Turning Tide',
  629: 'Rallying Cry',
  640: "Order's Wrath",
  641: "Serpent's Disdain",
  764: 'Highland Sentinel',
  802: "Arkay's Charity",
  817: 'Recovery Convergence',
  818: 'Perfected Recovery Convergence',
  827: 'Stonehulk Domination',

  // Crafted
  36: 'Armor of the Veiled Heritance',
  43: 'Armor of the Seducer',
  54: 'Ashen Grip',
  62: "Hatchling's Shell",
  75: "Torug's Pact",
  92: "Kagrenac's Hope",
  105: 'Twin Sisters',
  126: 'Ancient Grace',
  193: 'Overwhelming',
  210: 'The Pariah',
  219: 'Morkuldin',
  242: "Pelinal's Wrath",
  323: "Assassin's Guile",
  326: "Vanguard's Challenge",
  338: 'Flame Blossom',
  581: 'Bog Raider',
  642: "Druid's Braid",

  // PvP / Utility
  112: 'Night Terror',
  305: 'Treasure Hunter',
  321: 'Defiler',
  355: 'Unfathomable Darkness',
  467: 'Dragonguard Elite',
  488: 'Venomous Smite',
  503: 'Wild Hunt',
  579: 'Frostbite',
  583: 'Heartland Conqueror',
  617: 'Plaguebreak',
  606: 'Thunder Caller',
  623: 'Storm-Cursed',
  671: 'Gourmand',
  675: 'Stormweaver',
  690: "Akatosh's Law",
  754: "Oakfather's Retribution",
  757: 'The Weald',
  805: 'Three Queens',
  806: 'Death-Dancer',

  // Other
  29: 'The Sergeant',
  46: 'The Noble Duelist',
  61: 'Dreugh King Slayer',
  77: 'The Crusader',
  84: 'Prismatic Weapon',
  140: 'Aether',
  171: 'Eternal Yokeda',
  173: 'Vicious Ophidian',
  187: 'Swamp Raider',
  188: 'Storm Master',
  190: 'Scathing Mage',
  198: 'Essence Thief',
  204: 'Endurance',
  206: 'Agility',
  281: 'Armor of the Trainee',
  293: 'Plague Doctor',
  347: 'Plague Slinger',
  475: 'Aegis Caller',
  603: "Scorion's Feast",
  845: "Huntsman's Warmask",
};

/**
 * Resolve a set ID to its display name.
 * Returns the name if known, or a "Set #ID" fallback for unrecognized IDs.
 */
export function getSetName(id: number): string {
  return SET_NAMES[id] ?? `Set #${id}`;
}
